# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_auto_20170110_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionresults',
            name='inspection_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 10, 20, 38, 14, 78716, tzinfo=utc)),
        ),
    ]
