# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_auto_20170110_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionresults',
            name='grade',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectionresults',
            name='inspection_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inspectionresults',
            name='inspection_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(default='American', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
