# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_auto_20170110_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='boro',
            field=models.CharField(default='Manhattan', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='building',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='street',
            field=models.CharField(default='Main St', max_length=50),
        ),
    ]
