# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_auto_20170110_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionresults',
            name='grade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='boro',
            field=models.CharField(default='Manhattan', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='building',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='Restaurant', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='street',
            field=models.CharField(default='Main St', max_length=100),
        ),
    ]
